server:
  port: 8080

spring:
  datasource:
    username: root
    password: 1985
    url: jdbc:mysql://localhost:3306/search_engine?useUnicode=true&characterEncoding=utf8&charSet=utf-8&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        useUnicode: true
        characterEncoding: utf8mb4
    hibernate:
      ddl-auto: update
    show-sql: true

indexing-settings:
  sites:

    - url: http://www.dombulgakova.ru/
      name: dombulgakova